### ISSUE TITLE
 Liste de mots du dictionnaire pour en sélectionner un aléatoirement ?

### ISSUE THREAD

**Issue by Naereen** [alexliebh/dmum#2]
Bonjour @alexliebh,
En lisant la description de ce projet, qui semble plutôt complet, je me demande : est-ce qu'il y a quelque part dans ce projet une liste de mots pour que le programme en sélectionne un automatiquement ? (j'ai cherché, sans trouver)
Merci d'avance !

**Comment by Naereen** [comment]
J'ai trouvé cette ligne
https://github.com/alexliebh/dmum/blob/ca65a8cebdaad98b499983b20d94247f2a8f3d66/data/util/LoadingUtil.java#L15
qui semble dire que les mots étaient stockés dans un fichier .csv dans le dossier `data/util/res` mais il n'est pas sur GitHub.
Merci d'avance :pray: !

**Comment by alexliebh** [comment]
Bonsoir,
Merci pour ce commentaire, il me permet de faire le ménage pour ce vieux projet.
Je vous ajouté les ressources dans le dossier du serveur et ajouté le frontend si vous voulez y jeter un coup d'oeil.
Bonne exploration @Naereen 😉

**Comment by Naereen** [comment]
Bonjour @alexliebh,
Merci, j'ai pu ajouter votre liste de mots !
Si vous êtes curieux, pour l'instant ce (mini mini) projet donne cette page web : https://naereen.github.io/Free-dictionnaries-for-Pictionnary/
Bonne continuation @alexliebh !
